version: '3.8'
services:
  mongo:
    image: mongo:5
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    environment:
      MONGO_URI: 'mongodb://mongo:27017/sf1db'
      JWT_SECRET: 'supersecretkey'
volumes:
  mongo_data: